collection/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from music.views import *
from settings import *

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^album/([0-9]+)?/$', album_view),
    url(r'^band/([0-9]+)?/$', band_view),

    #develop
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT}),
)

music/models.py
#-*- coding: utf-8 -*-
from django.db import models
import os


def album_cover_rename(instance, filename):
    path = 'album_pics'
    print(instance)
    ext = filename.split('.')[-1]
    filename = '%s%s.%s' % (instance.title, instance.id, ext)
    return os.path.join(path, filename)


def band_pic_rename(instance, filename):
    path = 'band_pics'
    print(instance)
    ext = filename.split('.')[-1]
    filename = '%s%s.%s' % (instance.name, instance.id, ext)
    return os.path.join(path, filename)


RATING_CHOICES = (
        (1, 'Ужасно'),
        (2, 'Плохо'),
        (3, 'Средне'),
        (4, 'Хорошо'),
        (5, 'Отлично'),
)

CATEGORY_CHOICES = (
        ('LP', 'LP'),
        ('EP', 'EP'),
        ('SINGLE', 'SINGLE'),
)


class Role(models.Model):
    title = models.CharField(max_length=30, verbose_name='Название')

    class Meta:
        verbose_name = 'роль'
        verbose_name_plural = 'роли'

    def __unicode__(self):
        return self.title


class Artist(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    surname = models.CharField(max_length=100, verbose_name='Фамилия')
    role = models.ForeignKey(Role, related_name='artists', verbose_name='Роль', null=True, blank=True)
    bio = models.TextField(verbose_name='Биография', blank=True, null=True)
    pic = models.ImageField(upload_to='artist_pics', verbose_name='Фотография', blank=True, null=True)

    class Meta:
        verbose_name = 'музыкант'
        verbose_name_plural = 'музыканты'

    def __unicode__(self):
        return '%s %s' % (self.name, self.surname)


class Band(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    bio = models.TextField(verbose_name='История', blank=True, null=True)
    start_year = models.SmallIntegerField(verbose_name='Год основания', null=True)
    finish_year = models.SmallIntegerField(verbose_name='Год распада', null=True, blank=True)
    pic = models.ImageField(upload_to=band_pic_rename, verbose_name='Фотография', blank=True, null=True)
    artists = models.ManyToManyField(Artist, related_name='bands', verbose_name='Участники')

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'

    def __unicode__(self):
        return self.name


class Album(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    rating = models.SmallIntegerField(choices=RATING_CHOICES, verbose_name='Оценка')
    year = models.DateField(verbose_name='Дата выхода', blank=True, null=True)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES, verbose_name='Категория', default='LP')
    bio = models.TextField(verbose_name='Описание', blank=True, null=True)
    pic = models.ImageField(upload_to=album_cover_rename, verbose_name='Обложка', blank=True, null=True)
    band = models.ForeignKey(Band, related_name='albums', verbose_name='Группа')

    class Meta:
        verbose_name = 'альбом'
        verbose_name_plural = 'альбомы'

    def __unicode__(self):
        return self.title


class Track(models.Model):
    number = models.SmallIntegerField(verbose_name='Номер')
    title = models.CharField(max_length=100, verbose_name='Название')
    rating = models.SmallIntegerField(choices=RATING_CHOICES, verbose_name='Оценка')
    lyric = models.TextField(verbose_name='Текст', blank=True, null=True)
    album = models.ForeignKey(Album, related_name='tracks', verbose_name='Альбом')

    class Meta:
        verbose_name = 'песня'
        verbose_name_plural = 'песни'

    def __unicode__(self):
        return '%s: %s' % (self.album, self.title)

music/forms.py
from django import forms
from models import Album


class AddAlbum(forms.ModelForm):
    class Meta:
        model = Album
        fields = ('title', 'year', 'category', 'pic', 'bio')

music/views.py
from django.shortcuts import render_to_response
from music.models import *
from music.forms import *


def album_view(request, album_id):
    album = Album.objects.get(id=album_id)
    tracks = album.tracks.order_by('number')
    print(album)
    return render_to_response('album_view.html', {'album': album, 'tracks': tracks})


def band_view(request, album_id):
    band = Band.objects.get(id=album_id)
    print(band)
    album_form = AddAlbum()
    albums = band.albums.order_by('-year')
    return render_to_response('band_view.html', {'band': band, 'albums': albums, 'album_form': album_form})


def create_task(request):
    if request.method == 'POST':
        form = AddAlbum(request.POST, request.FILES,)
        if form.is_valid():
            album = form.save(commit=False)
            if not task.task_photo:
                number = random.randint(1,6)
                task.task_photo = 'task_photos/page4-img'+str(number)+'.jpg'
            task.user = request.user
            task.save()
            return redirect('/task/'+str(task.id))
    return HttpResponseBadRequest()

templates/album_view.html
{% extends 'base.html' %} {% block title %}Альбом: {{ album.title }}{% endblock %} {% block css %} {% load static from staticfiles %}
<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/album.css' %}"> {% endblock %} {% block content %}

<body>
  <h6>{{ album.band }}:<br /><span>{{ album.title }}</span><br /><br />{{ album.band }}:<br /><span>{{ album.title }}</span></h6>
  <div class="head">
    <a href="/band/{{ album.band.id }}"><img border="0" class="arrow" src="{% static 'img/arrow.png' %}" title="Вернуться к группе {{ album.band }}">
    </a>
    <h1>{{ album.title }}</h1>
  </div>
  <div class="w-container gradient-filling">
    <div class="subject">
      <div class="section subject-pic">
        <div class="pic-holder">
          <img class="pic shadow" src="/media/{{ album.pic|default:'album_pics/nocover.jpg' }}" alt="{{ album.title }}">
          <div class="label shadow">
            <span>Оценка: {{ album.rating }}/5</span>
          </div>
        </div>
      </div>
      <div class="section list">
        <h2>Треклист:</h2>
        <ul>
          {% for track in tracks %} {% if track.rating > 2 %}
          <li style=" background: linear-gradient(0deg, rgba(233, 249, 0, 0.{{ track.rating|add:-3 }}) 65%, rgba(0,0,0,0));">{{ track.number }}. <b>{{ track.title }}</b>
          </li>
          {% else %}
          <li style=" background: linear-gradient(0deg, rgba(225, 225, 225, 0.{{ track.rating }}) 65%, rgba(0,0,0,0));">{{ track.number }}. <b>{{ track.title }}</b>
          </li>
          {% endif %} {% endfor %}
        </ul>
      </div>
      <div class="section text">
        <h2>Описание альбома:</h2>
        <p>{{ album.bio }}</p>
      </div>
    </div>
  </div>
</body>
{% endblock %}

templates/band_view.html
{% extends 'base.html' %} {% block title %}Группа: {{ band.name }}{% endblock %} {% block css %} {% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/band.css' %}">
<script type="text/javascript">
  <!--
  function toggle_visibility(id) {
      var e = document.getElementById(id);
      if (e.style.display == 'block')
        e.style.display = 'none';
      else
        e.style.display = 'block';
    }
    //-->
</script>
{% endblock %} {% block content %}

<body>
  <h6>{{ band.name }}:<br /><span>{% for artist in band.artists.all %}{{ artist.name }} {{ artist.surname }}<br />{% endfor %}</span></h6>
  <div class="head">
    <a href="/bands/"><img border="0" class="arrow" src="{% static 'img/arrow.png' %}" title="Все группы">
    </a>
    <h1>{{ band.name }}</h1>
  </div>
  <div class="w-container gradient-filling">
    <div class="subject">
      <div class="section subject-pic">
        <div class="w-clearfix pic-holder"><img class="pic shadow" src="/media/{{ band.pic|default:'album_pics/nocover.jpg' }}" alt="{{ band.name }}">
          <div class="label shadow">
            <span>{{ band.start_year }} - {{ band.finish_year|default_if_none:'наши дни' }}</span>
          </div>
        </div>
      </div>
      <div class="section list w-clearfix">
        <h2>Учасники:</h2>
        <ul>
          {% for artist in band.artists.all %}
          <li style=" background: linear-gradient(0deg, rgba(233, 249, 0, 0.{{ album.rating|add:-3 }}) 65%, rgba(0,0,0,0));">
            <b>{{ artist.name }} {{ artist.surname }}</b>
          </li>
          {% endfor %}
        </ul>
      </div>
      <div class="section grid w-clearfix">
        <h2>Альбомы:</h2>
        <div class="w-row grid">
          {% for album in albums %}
          <div class="w-col w-col-6">
            <a href="/album/{{ album.id }}">
              <div class="pic-holder">
                <img class="pic shadow" src="/media/{{ album.pic|default:'album_pics/nocover.jpg' }}" title="Перейти к альбому {{ album.title }}">
                <div class="label shadow">
                  <span>
                    {% if album.title|length > 50 %}
                    {{ album.title|slice:'20' }}..
                    {% else %}
                    {{ album.title }}
                    {% endif %}
                  </span>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
          <div class="w-col w-col-6">
            <a href="#">
              <div class="pic-holder">
                <img class="pic" src="{% static 'img/plus.png' %}" onclick="toggle_visibility('add');" title="Добавить альбом">
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="section  w-clearfix add-album" style="display: none" id="add">
        <h2>Добавление альбома:</h2>
        <form method="POST" class="form" action="/changealbum/" enctype="multipart/form-data" id="add-album-form">
          <input placeholder="Название альбома" id="id_title" maxlength="100" name="title" type="text">
          <select id="id_category" name="category">
            <option value="LP" selected="selected">LP</option>
            <option value="EP">EP</option>
            <option value="SINGLE">SINGLE</option>
          </select>
          <input type="submit" class="button" value="Продолжить">
        </form>
      </div>
      <div class="text section w-clearfix">
        <h2>История группы:</h2>
        <p>{{ band.bio }}</p>
      </div>
    </div>
  </div>
</body>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head lang="en">
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  {% block css %}{% endblock %}
</head>

<body>
  {% block content %}{% endblock %}
</body>

</html>